version: '3.8'

services:
  api-gateway:
    container_name: api_gateway 
    build: ./
    ports:
      - "8077:8077"
    networks:
      - global-network

# Docker Networks
networks:
  global-network:
    external: true
