version: '3.8'

services:
  api-gateway:
    container_name: learning_service 
    build: ./
    ports:
      - "8070:8070"
    networks:
      - global-network

# Docker Networks
networks:
  global-network:
    external: true
