version: '3.8'

services:
  api-gateway:
    container_name: auth_service 
    build: ./
    ports:
      - "8085:8085"
    networks:
      - global-network

# Docker Networks
networks:
  global-network:
    external: true
